apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdgsj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdgsj
  template:
    metadata:
      labels:
        app: qdgsj
    spec:
      containers:
      - image: okteto.dev/qdgsj:latest
        name: qdgsj
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e575f412-683c-463b-835a-05b6ee94e2e5"
        - name: Vless_Path
          value: "/vl123"
        - name: Vmess_UUID
          value: "e575f412-683c-463b-835a-05b6ee94e2e5"
        - name: Vmess_Path
          value: "/vm456"
        - name: Share_Path
          value: "/v2link"
